In [1]:
import numpy as np

In [3]:
array1 = np.array([1,2,4,5])
array1

array([1, 2, 4, 5])

In [4]:
array2 = np.array([[1,2,4,5],[1,2,4,5]])
array2

array([[1, 2, 4, 5],
       [1, 2, 4, 5]])

In [5]:
array3 = np.array([[1,2,4,5],[1,2,4,5]])
array3

array([[1, 2, 4, 5],
       [1, 2, 4, 5]])

In [7]:
ones = np.ones((1,10))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
zeros = np.zeros((1,4))
zeros

array([[0., 0., 0., 0.]])

In [9]:
np.random.random((2,2))

array([[0.8830488 , 0.50104068],
       [0.42341137, 0.08297919]])

In [11]:
np.empty((5,5))

array([[ 5.03395435e-310,  0.00000000e+000,  0.00000000e+000,
        -1.00000000e+000,  1.00000000e+000],
       [-2.00000000e+000,  2.00000000e+000, -1.00000000e+000,
         1.00000000e+000,  0.00000000e+000],
       [ 2.00000000e+000,  1.00000000e+000,  1.00000000e+000,
         2.00000000e+000,  0.00000000e+000],
       [ 1.00000000e+000, -1.00000000e+000,  2.00000000e+000,
        -2.00000000e+000,  1.00000000e+000],
       [-1.00000000e+000,  0.00000000e+000, -2.00000000e+000,
        -1.00000000e+000,  1.02765654e-321]])

In [12]:
rangearr = np.arange(10,25,3)
rangearr

array([10, 13, 16, 19, 22])

In [14]:
np.linspace(2,9,12)

array([2.        , 2.63636364, 3.27272727, 3.90909091, 4.54545455,
       5.18181818, 5.81818182, 6.45454545, 7.09090909, 7.72727273,
       8.36363636, 9.        ])