In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([6,7,8,9])


In [3]:
np.add(arr1,arr2)

array([ 7,  9, 11, 13])

In [4]:
np.subtract(arr1,arr2)

array([-5, -5, -5, -5])

In [5]:
np.multiply(arr1,arr2)

array([ 6, 14, 24, 36])

In [6]:
np.divide(arr1,arr2)

array([0.16666667, 0.28571429, 0.375     , 0.44444444])